"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, FolderOpen, FolderPlus, Search, ShieldCheck, X } from "lucide-react";
import { createPortal } from "react-dom";
import { useApp } from "@/components/providers/app-provider";
import { useHardware } from "@/components/providers/hardware-provider";
import { Button, Panel, Pill, cx } from "@/components/ui/primitives";
import { Field, Select, TextArea, TextInput } from "@/components/ui/form";
import { PLACE_KINDS } from "@/lib/domain/vocab";
import { caseChain } from "@/lib/domain/records";
import type { CaseRecord } from "@/lib/domain/types";

const ACTIVE_KEY = "evidence-chain.active-case";

/**
 * The case a capture screen is working in.
 *
 * Held in the URL (?case=…) when present, otherwise in this browser, so a
 * capture always names the case it will append to. Nothing is captured until
 * a case has been chosen or created — an existing case is never entered by
 * accident.
 */
export function useActiveCase(): {
  caseRef: string | null;
  kase: CaseRecord | null;
  setCase: (ref: string | null) => void;
} {
  const { store } = useApp();
  const [caseRef, setRef] = React.useState<string | null>(null);

  React.useEffect(() => {
    const fromUrl = new URLSearchParams(window.location.search).get("case");
    if (fromUrl) {
      setRef(fromUrl);
      try {
        window.localStorage.setItem(ACTIVE_KEY, fromUrl);
      } catch {
        /* storage unavailable */
      }
      return;
    }
    try {
      setRef(window.localStorage.getItem(ACTIVE_KEY));
    } catch {
      /* storage unavailable */
    }
  }, []);

  const setCase = React.useCallback((ref: string | null) => {
    setRef(ref);
    try {
      if (ref) window.localStorage.setItem(ACTIVE_KEY, ref);
      else window.localStorage.removeItem(ACTIVE_KEY);
    } catch {
      /* storage unavailable */
    }
  }, []);

  const kase = store?.cases.find((c) => c.case_ref === caseRef) ?? null;
  // A remembered case that no longer exists must not linger.
  React.useEffect(() => {
    if (caseRef && store && !kase) setCase(null);
  }, [caseRef, store, kase, setCase]);

  return { caseRef: kase ? caseRef : null, kase, setCase };
}

/** Records already in a case, and the position the next one will take. */
export function useCasePosition(caseRef: string | null) {
  const { store } = useApp();
  if (!store || !caseRef) return { count: 0, nextPosition: 1, isNew: true };
  const chain = caseChain(store.records, caseRef);
  const highest = chain.reduce((acc, r, i) => Math.max(acc, r.case_seq ?? i + 1), 0);
  return { count: chain.length, nextPosition: highest + 1, isNew: chain.length === 0 };
}

/* ------------------------------------------------------------ new case */

/**
 * Create a case. The reference is generated by the server from the existing
 * case-numbering scheme; it is never typed, so two operators cannot invent the
 * same one.
 */
export function NewCaseDialog({
  open,
  onClose,
  onCreated,
}: {
  open: boolean;
  onClose: () => void;
  onCreated?: (caseRef: string) => void;
}) {
  const { store, officer, run } = useApp();
  const hw = useHardware();
  const [place, setPlace] = React.useState("Platform 3, Demo Junction (DMJ)");
  const [placeKind, setPlaceKind] = React.useState<string>(PLACE_KINDS[0]);
  const [purpose, setPurpose] = React.useState("");
  const [notes, setNotes] = React.useState("");
  const [busy, setBusy] = React.useState(false);

  React.useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open || !store) return null;

  const device =
    store.devices.find((d) => d.assigned_officer_id === officer?.officer_id) ??
    store.devices.find((d) => d.force === officer?.force) ??
    null;

  const create = async () => {
    if (!officer || !device) return;
    setBusy(true);
    const res = await run<CaseRecord>(
      "case.create",
      {
        officer_id: officer.officer_id,
        device_id: device.device_id,
        place,
        place_kind: placeKind,
        purpose,
        notes,
      },
      { toast: { title: "New case created", body: "It starts its own chain, with no records yet." } },
    );
    setBusy(false);
    if (res.ok && res.result) {
      onClose();
      onCreated?.(res.result.case_ref);
    }
  };

  return createPortal(
    <div className="fixed inset-0 z-[85] flex items-end justify-center sm:items-center">
      <div className="absolute inset-0 animate-[fade-in_.2s_ease-out] bg-[#252525]/35" onClick={onClose} />
      <Panel
        solid
        className="relative m-0 max-h-[94vh] w-full max-w-[520px] animate-fade-up overflow-y-auto rounded-b-none sm:m-4 sm:rounded-panel"
      >
        <div className="flex items-start justify-between gap-3 border-b border-line px-5 py-4">
          <div>
            <div className="label">Case management</div>
            <h2 className="mt-1 text-[20px] font-semibold tracking-tight text-brand-deep">
              Create New Evidence Case
            </h2>
          </div>
          <button
            aria-label="Cancel"
            onClick={onClose}
            className="flex h-10 w-10 items-center justify-center rounded-xl text-fg-dim hover:bg-ink-750 hover:text-fg"
          >
            <X size={18} />
          </button>
        </div>

        <div className="space-y-4 px-5 py-5">
          <div className="rounded-2xl border border-brand/25 bg-brand-soft/60 px-4 py-3.5">
            <div className="label">Case reference</div>
            <div className="mono mt-1 text-[18px] font-semibold text-brand-deep">AUTO GENERATED</div>
            <p className="mt-1 text-[13.5px] leading-relaxed text-fg-muted">
              This creates a new independent evidence chain. The next reference in the existing series
              is assigned when you create it, and the first record will be position 1.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Operator" hint="Current officer — never typed">
              <TextInput value={officer ? `${officer.name} · ${officer.officer_id}` : ""} readOnly disabled />
            </Field>
            <Field label="Signing device" hint="The handset that signs this case's records">
              <TextInput value={device?.device_id ?? "—"} readOnly disabled />
            </Field>
            <Field
              className="sm:col-span-2"
              label="Sensor device"
              hint={hw.isPramaan ? "Readings can be captured into this case" : "Optional — manual entry works without it"}
            >
              <TextInput
                value={
                  hw.isPramaan && hw.state === "connected"
                    ? `PRAMAAN · ${hw.deviceId ?? "connected"}`
                    : hw.transport === "demo"
                      ? "Demo device (simulated)"
                      : "PRAMAAN · not connected"
                }
                readOnly
                disabled
              />
            </Field>
            <Field label="Place" required>
              <TextInput value={place} onChange={(e) => setPlace(e.target.value)} />
            </Field>
            <Field label="Place kind" required>
              <Select value={placeKind} onChange={(e) => setPlaceKind(e.target.value)}>
                {PLACE_KINDS.map((k) => (
                  <option key={k} value={k}>
                    {k}
                  </option>
                ))}
              </Select>
            </Field>
          </div>

          <Field label="Purpose / event type" hint="Optional. Shown as the case title.">
            <TextInput
              value={purpose}
              onChange={(e) => setPurpose(e.target.value)}
              placeholder="e.g. Platform stop — suspected narcotics"
            />
          </Field>
          <Field label="Notes" hint="Optional">
            <TextArea value={notes} onChange={(e) => setNotes(e.target.value)} rows={2} />
          </Field>
        </div>

        <div className="sticky bottom-0 flex gap-2.5 border-t border-line bg-white/90 px-5 py-4 backdrop-blur-sm">
          <Button variant="secondary" className="flex-1" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="primary"
            className="flex-1"
            busy={busy}
            disabled={busy || !place.trim() || !officer || !device}
            icon={<FolderPlus size={16} />}
            onClick={create}
          >
            Create Case
          </Button>
        </div>
      </Panel>
    </div>,
    document.body,
  );
}

/* ---------------------------------------------------------- case picker */

/** Choose which existing case to work in. Explicit, never a silent default. */
export function CasePickerDialog({
  open,
  onClose,
  onPick,
}: {
  open: boolean;
  onClose: () => void;
  onPick: (caseRef: string) => void;
}) {
  const { store } = useApp();
  const [q, setQ] = React.useState("");

  React.useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open || !store) return null;

  const needle = q.trim().toLowerCase();
  const cases = store.cases.filter(
    (c) =>
      !needle ||
      c.case_ref.toLowerCase().includes(needle) ||
      c.place.toLowerCase().includes(needle) ||
      c.title.toLowerCase().includes(needle),
  );

  return createPortal(
    <div className="fixed inset-0 z-[85] flex items-end justify-center sm:items-center">
      <div className="absolute inset-0 animate-[fade-in_.2s_ease-out] bg-[#252525]/35" onClick={onClose} />
      <Panel
        solid
        className="relative m-0 max-h-[90vh] w-full max-w-[560px] animate-fade-up overflow-y-auto rounded-b-none sm:m-4 sm:rounded-panel"
      >
        <div className="flex items-start justify-between gap-3 border-b border-line px-5 py-4">
          <div>
            <div className="label">Case management</div>
            <h2 className="mt-1 text-[20px] font-semibold tracking-tight text-brand-deep">
              Choose an existing case
            </h2>
            <p className="mt-1 text-[13.5px] text-fg-muted">
              New records are appended. Nothing already in the case can change.
            </p>
          </div>
          <button
            aria-label="Close"
            onClick={onClose}
            className="flex h-10 w-10 items-center justify-center rounded-xl text-fg-dim hover:bg-ink-750 hover:text-fg"
          >
            <X size={18} />
          </button>
        </div>

        <div className="px-5 py-4">
          <div className="relative">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-fg-dim" />
            <TextInput
              className="pl-9"
              aria-label="Search cases"
              placeholder="Case ID, place or title"
              value={q}
              onChange={(e) => setQ(e.target.value)}
            />
          </div>
        </div>

        <ul className="divide-y divide-line">
          {cases.map((c) => {
            const chain = caseChain(store.records, c.case_ref);
            return (
              <li key={c.case_ref}>
                <button
                  type="button"
                  onClick={() => {
                    onPick(c.case_ref);
                    onClose();
                  }}
                  className="flex w-full items-center gap-3 px-5 py-3.5 text-left transition-colors hover:bg-brand/[0.05]"
                >
                  <FolderOpen size={18} className="shrink-0 text-brand" />
                  <span className="min-w-0 flex-1">
                    <span className="mono block text-[14px] font-semibold text-fg">{c.case_ref}</span>
                    <span className="block truncate text-[13px] text-fg-muted">{c.place}</span>
                  </span>
                  <Pill tone={chain.length ? "neutral" : "brand"}>
                    {chain.length ? `${chain.length} record${chain.length === 1 ? "" : "s"}` : "Empty"}
                  </Pill>
                  <ArrowRight size={16} className="shrink-0 text-fg-dim" />
                </button>
              </li>
            );
          })}
          {cases.length === 0 ? (
            <li className="px-5 py-8 text-center text-[13.5px] text-fg-muted">No case matches “{q}”.</li>
          ) : null}
        </ul>
      </Panel>
    </div>,
    document.body,
  );
}

/* ------------------------------------------------------- context banner */

/**
 * The case a capture screen will write into, stated before anything is typed,
 * with the two ways to change it: open a different case, or start a new one.
 */
export function CaseContextBar({
  caseRef,
  onPick,
  className,
}: {
  caseRef: string | null;
  onPick: (ref: string | null) => void;
  className?: string;
}) {
  const { store } = useApp();
  const router = useRouter();
  const [newOpen, setNewOpen] = React.useState(false);
  const [pickOpen, setPickOpen] = React.useState(false);
  const { count, nextPosition, isNew } = useCasePosition(caseRef);
  const kase = store?.cases.find((c) => c.case_ref === caseRef) ?? null;

  return (
    <>
      <div
        className={cx(
          "flex flex-col gap-3 rounded-2xl border bg-white p-4 shadow-chip sm:flex-row sm:items-center",
          kase ? "border-line" : "border-warn/40",
          className,
        )}
      >
        <div className="min-w-0 flex-1">
          <div className="label">Case</div>
          {kase ? (
            <>
              <div className="mt-1 flex flex-wrap items-center gap-2">
                <Link
                  href={`/cases/${kase.case_ref}`}
                  className="mono text-[18px] font-semibold text-brand-deep hover:underline"
                >
                  {kase.case_ref}
                </Link>
                <Pill tone={isNew ? "brand" : "neutral"}>{isNew ? "New case" : "Existing case"}</Pill>
                <Pill tone="neutral">
                  {count} record{count === 1 ? "" : "s"}
                </Pill>
              </div>
              <p className="mt-1 text-[13.5px] leading-relaxed text-fg-muted">
                {kase.place} · This capture is appended as position {nextPosition} of this case.
                {isNew ? " It starts the chain." : " Nothing already recorded can change."}
              </p>
            </>
          ) : (
            <>
              <div className="mt-1 text-[16px] font-semibold text-fg">No case selected</div>
              <p className="mt-0.5 text-[13.5px] leading-relaxed text-fg-muted">
                Start a new case, or open an existing one, before capturing evidence.
              </p>
            </>
          )}
        </div>

        <div className="flex flex-wrap gap-2">
          <Button icon={<FolderPlus size={16} />} onClick={() => setNewOpen(true)}>
            New Case
          </Button>
          <Button icon={<FolderOpen size={16} />} onClick={() => setPickOpen(true)}>
            {kase ? "Change Case" : "Existing Cases"}
          </Button>
        </div>
      </div>

      <NewCaseDialog
        open={newOpen}
        onClose={() => setNewOpen(false)}
        onCreated={(ref) => {
          onPick(ref);
          router.push(`/cases/${ref}`);
        }}
      />
      <CasePickerDialog open={pickOpen} onClose={() => setPickOpen(false)} onPick={onPick} />
    </>
  );
}

/** Small reassurance used on read-only history views. */
export function ImmutableBadge({ className }: { className?: string }) {
  return (
    <span
      className={cx(
        "inline-flex items-center gap-1.5 rounded-full border border-ok/25 bg-ok/[0.07] px-2.5 py-1 text-[12px] font-semibold text-[#1F6A43]",
        className,
      )}
      title="Recorded evidence cannot be edited, reordered or deleted."
    >
      <ShieldCheck size={13} />
      Immutable record
    </span>
  );
}
